# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_topic_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
