# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 12:33
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20180418_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
    ]
